behaviors:
  PlatformerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 10000
