# Name: Chris Harvey, Ian Collins, Ryan Strong, Henry Chaffin, Kenny Meade
# Date: 10/17/2024
# Course: EECS 581
# Purpose: this is the config file for the PPO agent which is learning how to play the platformer game. This adjusts how it thinks and acts but mostly augments the AI's brain.

behaviors:
  PlatformerAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048            # Increased batch size
      buffer_size: 81920          # Increased buffer size
      learning_rate: 0.0001       # Slightly increased learning rate
      beta: 0.01                  # Increased entropy coefficient for better exploration
      epsilon: 0.2                # Standard PPO clipping
      lambd: 0.95                 # Standard GAE parameter
      num_epoch: 5                # Increased number of epochs per update
      shared_critic: False        # Separate networks for actor and critic
      learning_rate_schedule: linear
      beta_schedule: linear
      epsilon_schedule: linear
    network_settings:
      normalize: True
      hidden_units: 512           # Increased hidden units
      num_layers: 3               # Increased number of layers
      vis_encode_type: resnet     # If using visual inputs
      deterministic: False
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    init_path: None
    keep_checkpoints: 10
    checkpoint_interval: 500000
    max_steps: 100000000
    time_horizon: 1000
    summary_freq: 10000
    threaded: False

